# Data sources

We only have one dataset which is collected from the NYC OpenData which contains information that is collected and maintained by the City government. The reason why we choose the NYC openData is because we could directly get the data we are interested free without any additional operations and their data are real and reliable. Out dataset is the Motor Vehicle Collisions which contains details on the crash event and each row represents a motor crash event and the information about the crash reported from the engaged police. Since this dataset contains 31 columns and some columns are not that usefull for our analyze, we will do some preprocessing to the dataset and we will explain how we change the dataset in the cleaning section. For the following content, we will just explain what does each column represents. 

## Motor Vehicle Coliisions dataset
### Location variables
- `crash_date`: Occurrence date of collision
- `crash_time`: Occurrence time of collision
- `borough`: Borough where collision occurred
- `zip_code`: Postal code of incident occurrence
- `latitude`: Latitude coordinate for Global Coordinate System, WGS 1984, decimal degrees (EPSG 4326)
- `longitude`: Longitude coordinate for Global Coordinate System, WGS 1984, decimal degrees (EPSG 4326)
- `location`: Latitude , Longitude pair
- `on_street_name`: Street on which the collision occurred
- `cross_street_name`: Nearest cross street to the collision
- `off_street_name`: Street address if known

### Accident severity variables
- `number_of_persons_injured`: Number of persons injured
- `number_of_persons_killed`: Number of persons killed
- `number_of_pedestrians_injured`: Number of pedestrians injured
- `number_of_pedestrians_killed`: Number of pedestrians killed
- `number_of_cyclist_injured`: Number of cyclists injured
- `number_of_cyclist_killed`: Number of cyclists killed
- `number_of_motorist_injured`: Number of vehicle occupants injured
- `number_of_motorist_killed`: Number of vehicle occupants killed

### Accident factor variables
- `contributing_factor_vehicle_1`: Factors contributing to the collision for designated vehicle
- `contributing_factor_vehicle_2`: Factors contributing to the collision for designated vehicle
- `contributing_factor_vehicle_3`: Factors contributing to the collision for designated vehicle
- `contributing_factor_vehicle_4`: Factors contributing to the collision for designated vehicle
- `contributing_factor_vehicle_5`: Factors contributing to the collision for designated vehicle
- `collision_id`:Unique record code generated by system. Primary Key for Crash table.
- `vehicle_type_code1`:Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other)
- `vehicle_type_code2`:Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other)
- `vehicle_type_code3`:Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other)
- `vehicle_type_code4`:Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other)
- `vehicle_type_code5`: Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other)