# Conclusion

## Valuable results
There are several meaningful ideas we have analyzed through our data visualization.

* The NYC motor collision is prevalent through all borough and there are regions like zipcode 11207 and 10002 that has comparatively higher motor collision rate than other places within each borough. People could pay more attention when walking or driving within those areas if they live in Brooklyn or Manhattan and in general people should obey the traffic rule and be careful for walking across street.

* We have also found that there is no relationship between borough and accident contribution factors. None of the factors are significant in specific borough, so we can conclude that accident occurence reason has no regional effects. 

* The last mosaic visualization provide the evidence that there is no positive relationship between accident reason severity and the number of people get hurt in the accident, but we are questioning that maybe the severity of the driving behavior is positively correlated with the lethal rate of the collision . Besides, the size of the vehicle is also not positively correlated with the number of people that gor hurt in the collision. We cannot infer how many people get injured or killed in the collision by the vehicle type involved in the collision. But we are think they are negatively correlated and more data is needed to prove it.

## Data Limitation
Our dataset contains complete collision cases in NYC, but each case lacks sufficient details to provide a better analysis. There are huge number of NA in each columns and we need to filter data with lacking essential variables. Specifically for question like injury and killed cases, there is no enough data to provide a general trends. If the dataset contains more cases with people killed with categorical reasons, We can give a more meaningful analysis on which type of accidents are most severe and find the borough trend based on that. 

## Future direction
Though there is no significant relationship between the factors we focus and there is also no collision rate to give a comprehensive guideline for pedestrian or drivers, our results are still meaningful in current steps. When we proved combine people hurt and killed as the same varible,  we find some hidden relationships like maybe the higher level of severity of driving behaviro, the higher death rated caused which worth more investigation and maybe thousands of people will be saved from the collisions. Thus, when data contains more details, we could give a clearly relationship and investigation on the potential topics that we mentioned previously. Also, the current investigation on borough is on general region, another direction is a better use of representing those zipcode regional collisions rate in a map when data are large. Then we could have a better visualization of corresponding reginal collisions rate for different area on the map.

## Project invokes
This project gives us a better understanding of how motocycle collisions are threating people's lifes. There are relationships that we thought in general thoughts are wrong which means accident severity is also not single variable related and there might be many other factors related with the people that got hurt in the collision. We could use different data visualization to focus on different problems. Correct usage of visualization type on each question are audience friendly and representative. Each step of the project is essential part to analyse real world problem and tell audience what we find.